/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Element = IDL.Variant({
  'Grass' : IDL.Null,
  'Water' : IDL.Null,
  'Electric' : IDL.Null,
  'Earth' : IDL.Null,
});
export const MutationVariant = IDL.Variant({
  'Gradient' : IDL.Null,
  'Solid' : IDL.Null,
  'Metallic' : IDL.Null,
  'Spotted' : IDL.Null,
  'Striped' : IDL.Null,
});
export const BodyPart = IDL.Record({
  'element' : Element,
  'mutation' : MutationVariant,
});
export const NewWorm = IDL.Record({
  'element' : Element,
  'body' : BodyPart,
  'head' : BodyPart,
  'tail' : BodyPart,
});
export const WormId = IDL.Nat;
export const Worm = IDL.Record({
  'id' : WormId,
  'element' : Element,
  'body' : BodyPart,
  'head' : BodyPart,
  'tail' : BodyPart,
});

export const idlService = IDL.Service({
  'addWorm' : IDL.Func(
      [NewWorm],
      [IDL.Variant({ 'ok' : WormId, 'err' : IDL.Text })],
      [],
    ),
  'deleteWorm' : IDL.Func(
      [WormId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getWorms' : IDL.Func([], [IDL.Vec(Worm)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Element = IDL.Variant({
    'Grass' : IDL.Null,
    'Water' : IDL.Null,
    'Electric' : IDL.Null,
    'Earth' : IDL.Null,
  });
  const MutationVariant = IDL.Variant({
    'Gradient' : IDL.Null,
    'Solid' : IDL.Null,
    'Metallic' : IDL.Null,
    'Spotted' : IDL.Null,
    'Striped' : IDL.Null,
  });
  const BodyPart = IDL.Record({
    'element' : Element,
    'mutation' : MutationVariant,
  });
  const NewWorm = IDL.Record({
    'element' : Element,
    'body' : BodyPart,
    'head' : BodyPart,
    'tail' : BodyPart,
  });
  const WormId = IDL.Nat;
  const Worm = IDL.Record({
    'id' : WormId,
    'element' : Element,
    'body' : BodyPart,
    'head' : BodyPart,
    'tail' : BodyPart,
  });
  
  return IDL.Service({
    'addWorm' : IDL.Func(
        [NewWorm],
        [IDL.Variant({ 'ok' : WormId, 'err' : IDL.Text })],
        [],
      ),
    'deleteWorm' : IDL.Func(
        [WormId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getWorms' : IDL.Func([], [IDL.Vec(Worm)], []),
  });
};

export const init = ({ IDL }) => { return []; };