/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BodyPart { 'element' : Element, 'mutation' : MutationVariant }
export type Element = { 'Grass' : null } |
  { 'Water' : null } |
  { 'Electric' : null } |
  { 'Earth' : null };
export type MutationVariant = { 'Gradient' : null } |
  { 'Solid' : null } |
  { 'Metallic' : null } |
  { 'Spotted' : null } |
  { 'Striped' : null };
export interface NewWorm {
  'element' : Element,
  'body' : BodyPart,
  'head' : BodyPart,
  'tail' : BodyPart,
}
export interface Worm {
  'id' : WormId,
  'element' : Element,
  'body' : BodyPart,
  'head' : BodyPart,
  'tail' : BodyPart,
}
export type WormId = bigint;
export interface _SERVICE {
  'addWorm' : ActorMethod<[NewWorm], { 'ok' : WormId } | { 'err' : string }>,
  'deleteWorm' : ActorMethod<[WormId], { 'ok' : null } | { 'err' : string }>,
  'getWorms' : ActorMethod<[], Array<Worm>>,
  'resetGame' : ActorMethod<[], Worm>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];