/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BodyPart {
    element: Element;
    mutation: MutationVariant;
}
export type WormId = bigint;
export interface Worm {
    id: WormId;
    element: Element;
    body: BodyPart;
    head: BodyPart;
    tail: BodyPart;
}
export interface NewWorm {
    element: Element;
    body: BodyPart;
    head: BodyPart;
    tail: BodyPart;
}
export enum Element {
    Grass = "Grass",
    Water = "Water",
    Electric = "Electric",
    Earth = "Earth"
}
export enum MutationVariant {
    Gradient = "Gradient",
    Solid = "Solid",
    Metallic = "Metallic",
    Spotted = "Spotted",
    Striped = "Striped"
}
export interface backendInterface {
    addWorm(newWorm: NewWorm): Promise<{
        __kind__: "ok";
        ok: WormId;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteWorm(id: WormId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getWorms(): Promise<Array<Worm>>;
}
import type { BodyPart as _BodyPart, Element as _Element, MutationVariant as _MutationVariant, NewWorm as _NewWorm, Worm as _Worm, WormId as _WormId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addWorm(arg0: NewWorm): Promise<{
        __kind__: "ok";
        ok: WormId;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorm(to_candid_NewWorm_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorm(to_candid_NewWorm_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_variant_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteWorm(arg0: WormId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorm(arg0);
                return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorm(arg0);
            return from_candid_variant_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorms(): Promise<Array<Worm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorms();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorms();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BodyPart_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BodyPart): BodyPart {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Element_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Element): Element {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_MutationVariant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MutationVariant): MutationVariant {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Worm_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Worm): Worm {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _WormId;
    element: _Element;
    body: _BodyPart;
    head: _BodyPart;
    tail: _BodyPart;
}): {
    id: WormId;
    element: Element;
    body: BodyPart;
    head: BodyPart;
    tail: BodyPart;
} {
    return {
        id: value.id,
        element: from_candid_Element_n14(_uploadFile, _downloadFile, value.element),
        body: from_candid_BodyPart_n16(_uploadFile, _downloadFile, value.body),
        head: from_candid_BodyPart_n16(_uploadFile, _downloadFile, value.head),
        tail: from_candid_BodyPart_n16(_uploadFile, _downloadFile, value.tail)
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    element: _Element;
    mutation: _MutationVariant;
}): {
    element: Element;
    mutation: MutationVariant;
} {
    return {
        element: from_candid_Element_n14(_uploadFile, _downloadFile, value.element),
        mutation: from_candid_MutationVariant_n18(_uploadFile, _downloadFile, value.mutation)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Grass: null;
} | {
    Water: null;
} | {
    Electric: null;
} | {
    Earth: null;
}): Element {
    return "Grass" in value ? Element.Grass : "Water" in value ? Element.Water : "Electric" in value ? Element.Electric : "Earth" in value ? Element.Earth : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Gradient: null;
} | {
    Solid: null;
} | {
    Metallic: null;
} | {
    Spotted: null;
} | {
    Striped: null;
}): MutationVariant {
    return "Gradient" in value ? MutationVariant.Gradient : "Solid" in value ? MutationVariant.Solid : "Metallic" in value ? MutationVariant.Metallic : "Spotted" in value ? MutationVariant.Spotted : "Striped" in value ? MutationVariant.Striped : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _WormId;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: WormId;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Worm>): Array<Worm> {
    return value.map((x)=>from_candid_Worm_n12(_uploadFile, _downloadFile, x));
}
function to_candid_BodyPart_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BodyPart): _BodyPart {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Element_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Element): _Element {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_MutationVariant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MutationVariant): _MutationVariant {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_NewWorm_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewWorm): _NewWorm {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    element: Element;
    body: BodyPart;
    head: BodyPart;
    tail: BodyPart;
}): {
    element: _Element;
    body: _BodyPart;
    head: _BodyPart;
    tail: _BodyPart;
} {
    return {
        element: to_candid_Element_n3(_uploadFile, _downloadFile, value.element),
        body: to_candid_BodyPart_n5(_uploadFile, _downloadFile, value.body),
        head: to_candid_BodyPart_n5(_uploadFile, _downloadFile, value.head),
        tail: to_candid_BodyPart_n5(_uploadFile, _downloadFile, value.tail)
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    element: Element;
    mutation: MutationVariant;
}): {
    element: _Element;
    mutation: _MutationVariant;
} {
    return {
        element: to_candid_Element_n3(_uploadFile, _downloadFile, value.element),
        mutation: to_candid_MutationVariant_n7(_uploadFile, _downloadFile, value.mutation)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Element): {
    Grass: null;
} | {
    Water: null;
} | {
    Electric: null;
} | {
    Earth: null;
} {
    return value == Element.Grass ? {
        Grass: null
    } : value == Element.Water ? {
        Water: null
    } : value == Element.Electric ? {
        Electric: null
    } : value == Element.Earth ? {
        Earth: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MutationVariant): {
    Gradient: null;
} | {
    Solid: null;
} | {
    Metallic: null;
} | {
    Spotted: null;
} | {
    Striped: null;
} {
    return value == MutationVariant.Gradient ? {
        Gradient: null
    } : value == MutationVariant.Solid ? {
        Solid: null
    } : value == MutationVariant.Metallic ? {
        Metallic: null
    } : value == MutationVariant.Spotted ? {
        Spotted: null
    } : value == MutationVariant.Striped ? {
        Striped: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
